// Matière des titres forgés et des descriptions.
// Paires [masculin, féminin] ; dans les phrases : {name} prénom, {e} « e » au féminin,
// {il}/{Il} il/elle, {le} le/la (complément), {lui} lui/elle (après préposition),
// {caste} personnage tiré, {title} titre forgé complet, {surnom} partie descriptive du titre.

window.ER_TITLES = {
  // Titres portés par des personnages du jeu (Chevalier limier Darriwil, Doigt sanglant Nerijus, Castellan Edgar…)
  honorifics: [
    ["Sir", "Dame"], ["Chevalier limier", "Chevalière limier"], ["Chevalier du Creuset", "Chevalière du Creuset"],
    ["Chevalier banni", "Chevalière bannie"], ["Chevalier royal", "Chevalière royale"], ["Chevalier carien", "Chevalière carienne"],
    ["Mage de guerre", "Mage de guerre"], ["Nécromancien", "Nécromancienne"], ["Parfumeur", "Parfumeuse"],
    ["Commandant", "Commandante"], ["Castellan", "Castellane"], ["Doigt sanglant", "Doigt sanglant"],
    ["Récusant", "Récusante"], ["Précepteur", "Préceptrice"], ["Sorcier", "Sorcière"], ["Gardien", "Gardienne"],
    ["Maître forgeron", "Maîtresse forgeronne"], ["Chasseur de sorcières", "Chasseuse de sorcières"],
  ],
  dlcHonorifics: [
    ["Chevalier aiguille", "Chevalière aiguille"], ["Chevalier noir", "Chevalière noire"],
    ["Lame de la Nuit", "Lame de la Nuit"], ["Chevalier de feu", "Chevalière de feu"],
  ],
  // Lieux de l'Entre-terre
  places: [
    "de Nécrolimbe", "de Liurnia", "de Caelid", "de Raya Lucaria", "de Leyndell", "de Farum Azula",
    "de Mohgwyn", "de Nokron", "de l'Arbre-Saint", "de Siofra", "de Sellia", "du mont Gelmir",
    "du plateau d'Altus", "du Manoir du Volcan", "de Caria", "d'Elphael", "de Morne",
  ],
  dlcPlaces: ["de l'Arbre-Ombre", "du Donjon de l'Ombre", "des terres de l'Ombre"],
};

window.ER_LORE = {
  chronicle: {
    openings: [
      "Quand le Cercle d'Elden vola en éclats, {name} était ailleurs, ce qu'{il} considère encore comme une circonstance atténuante.",
      "Rappelé{e} par la grâce après une mort longue et reposante, {name} a repris la route de l'Arbre-Monde sans conviction excessive.",
      "{name} a franchi la brume de Margit au onzième essai, ce qu'{il} présente désormais comme une stratégie.",
      "À la Table ronde, Hewg forge pour {name} sans lever les yeux, ce qui reste la plus haute marque d'estime du bâtiment.",
      "{name} a aidé Alexander, le guerrier-jarre, à sortir du trou où il méditait. Depuis, la jarre lui écrit.",
      "Rennala berce toujours son œuf d'ambre au fond de Raya Lucaria ; {name} reste la seule personne à avoir frappé avant d'entrer.",
      "{name} a vu Radahn retenir les étoiles, et en a surtout retenu le cheval, qui mérite selon {lui} une médaille.",
      "Kalé, à l'église d'Elleh, a vendu à {name} une lanterne, deux cartes et le sentiment d'avoir été compris{e}.",
      "Melina a proposé à {name} de convertir ses runes en force. {Il} a demandé s'il existait une formule sans engagement.",
      "Patches a surgi d'un coffre en hurlant, puis s'est rendu avec une telle sincérité que {name} lui a laissé un pourboire.",
      "Gurranq a confié à {name} une liste de racines de mort à rapporter, griffonnée au dos d'un très vieux parchemin.",
      "{name} a porté la poupée de Ranni pendant des semaines, en lui parlant de la météo pour meubler.",
      "Fia a proposé à {name} une étreinte au chevet des morts ; {il} a sollicité un délai de réflexion de quarante jours.",
      "Boc le couturier a retouché l'armure de {name} en signalant, avec tact, que ce n'était pas la taille du dessus.",
      "Morgott a fait savoir à {name} que les Sans-éclat ne sont pas les bienvenus à Leyndell ; {il} l'a noté dans le livre d'or.",
      "Au Manoir du Volcan, Tanith a confié un contrat à {name}, rédigé si petit qu'{il} l'a signé par lassitude.",
      "Roderika accorde désormais les esprits de {name} ; elle dit qu'ils chantent juste mais arrivent toujours en retard.",
      "{name} a suivi les messages au sol jusqu'au bord d'une falaise, puis un peu au-delà, par politesse.",
      "Le jour où {name} a compris que Marika et Radagon ne faisaient qu'un, {il} a relu tout son carnet avec un autre œil.",
      "{name} a gravi les Montagnes des Géants avec un manteau de mi-saison, par principe plus que par confort.",
      "Dans les égouts de Leyndell, {name} a rencontré des Réprouvés fort aimables, à condition de ne pas les regarder.",
      "Godrick a proposé à {name} de rejoindre sa collection de bras. {Il} a décliné poliment, en gardant les deux.",
    ],
    dlcOpenings: [
      "{name} a posé la main sur le bras desséché de Mohg et s'est réveillé{e} dans les terres de l'Ombre, sans bagages ni explication.",
      "Dans les terres de l'Ombre, {name} ramasse des fragments de l'Arbre-Ombre avec la ferveur d'un philatéliste.",
      "{name} a croisé Messmer l'Empaleur et garde de la rencontre une odeur de brûlé qui ne part pas au lavage.",
      "Leda a recruté {name} pour retrouver Miquella, puis a pris l'air vexé d'apprendre qu'{il} lisait les petites lignes.",
      "{name} a écouté Ansbach raconter Mohg pendant une soirée entière : c'était très documenté et légèrement inquiétant.",
      "Igon a enseigné à {name} la haine des dragons avec la patience d'un moniteur d'auto-école.",
    ],
    links: [
      "Les érudits de Raya Lucaria {le} classent, faute de mieux, parmi les « {caste} ».",
      "Un recensement de la Table ronde l'enregistre sous la mention « {caste} », suivie d'un point d'interrogation.",
      "On {le} dit apparenté{e} à « {caste} », par une branche que personne ne souhaite approfondir.",
      "Son dossier porte la cote « {caste} », qu'{il} conteste par lettre recommandée.",
      "Les bardes {le} confondent avec « {caste} » ; {il} a cessé de corriger, par économie.",
      "Sa ressemblance avec « {caste} » relève, selon {lui}, d'une coïncidence purement administrative.",
      "Le bestiaire officiel {le} range entre « {caste} » et la page déchirée qui suit.",
      "Une prophétie mineure annonçait « {caste} » ; {name} s'est présenté{e} à la place, et personne n'a osé protester.",
      "Sur les cartes de l'Entre-terre, son emplacement est simplement marqué « {caste}, probablement ».",
      "Quand on lui demande « {caste} ? », {il} répond « en quelque sorte », ce qui clôt généralement l'échange.",
    ],
    closings: [
      "On l'appelle désormais « {surnom} », titre qu'{il} a fait graver sur sa boîte aux lettres en lettres adhésives.",
      "Ses runes dorment sur un compte qui rapporte moins que ce que lui coûtent ses morts.",
      "{Il} tient un tableur de ses défaites, avec mise en forme conditionnelle.",
      "Son répondeur annonce : « {title} est actuellement en combat, merci de laisser une rune après le bip. »",
      "Le jour, {il} défie des demi-dieux ; le soir, {il} cherche en vain une vis manquante dans un meuble en kit.",
      "{Il} affirme avoir lu les conditions générales de la Volonté supérieure. Personne n'y croit, et c'est réciproque.",
      "Ses voisins ignorent tout de ses exploits, mais déplorent les coups de cloche à trois heures du matin.",
      "Son dernier mot avant chaque boss est « bon », prononcé sans la moindre conviction.",
      "{Il} garde ses fioles comme d'autres gardent leurs tickets de caisse : par principe, et sans jamais s'en servir.",
      "Sa devise, brodée sur un torchon : « Encore un essai, puis on verra. »",
      "À chaque résurrection, {il} vérifie d'abord que ses clés sont bien dans sa poche.",
      "Son médecin traitant a cessé de poser des questions après le troisième certificat de décès.",
      "{Il} a demandé un devis pour réparer l'Arbre-Monde ; le délai annoncé était raisonnable, le prix beaucoup moins.",
      "{Il} salue les ennemis qui réapparaissent, comme on salue un collègue croisé deux fois dans le même couloir.",
      "Au guichet des âmes, {il} a pris un ticket ; son numéro n'est toujours pas passé.",
      "{Il} possède trois armes légendaires et une seule paire de chaussettes intacte, ce qui en dit long sur ses priorités.",
      "{Il} dit « {surnom} » à la troisième personne pendant les repas de famille, et l'ambiance s'en ressent.",
      "{Il} a rangé sa Grande Rune dans le tiroir à piles, faute de mieux.",
    ],
  },
  testimony: {
    quotes: [
      ["Kalé, marchand", "« {name} m'achète toujours la même lanterne. Je crois qu'{il} les collectionne, ou qu'{il} a peur du noir. Je ne pose pas de questions. »"],
      ["Roderika", "« {name} m'apporte des cendres d'esprit comme d'autres apportent des fleurs. C'est touchant, quoiqu'un peu poussiéreux. »"],
      ["Patches", "« {name} ? Charmante personne. Je l'ai attendu{e} deux jours dans un coffre, et pas une fois je ne me suis ennuyé. »"],
      ["Varré au masque blanc", "« Je lui ai promis un avenir glorieux au palais de Mohgwyn. {Il} a demandé si la mutuelle était incluse. »"],
      ["Maître forgeron Hewg", "« {name} affûte ses lames chez moi depuis des années. Jamais un merci, mais {il} revient. Chez nous, ça suffit. »"],
      ["Melina", "« J'ai guidé bien des Sans-éclat. Aucun n'avait autant de remarques sur l'itinéraire que {name}. »"],
      ["Blaidd, le Demi-Loup", "« {name} hurle avec moi à la lune. Faux, mais avec beaucoup d'engagement. »"],
      ["Gowry", "« Quelle âme délicate que {name}. J'aimerais tant lui présenter ma fille. » (Il est recommandé de refuser.)"],
      ["Rennala", "« {name} suit mes cours depuis le fond de l'amphithéâtre. Je ne l'ai jamais vu{e}, mais j'entends sa plume. »"],
      ["D, Chasseur des morts", "« J'ai été formé pour traquer les morts qui ne restent pas morts. Pour {name}, j'ai ouvert un dossier à part. »"],
      ["Gurranq", "« RACINES. {name} rapporte racines. {name} bon. » (Traduction approximative.)"],
      ["Sorcière Sellen", "« {name} a du potentiel. Malheureusement, {il} a aussi un emploi du temps. »"],
      ["Alexander, guerrier-jarre", "« {name} m'a sorti d'un trou. Je lui dois la vie, et une grande partie de mon contenu. »"],
      ["Enia, liseuse de Doigts", "« Les Doigts ont parlé de {name}. Ils ont surtout soupiré. »"],
    ],
    dlcQuotes: [
      ["Sir Ansbach", "« J'ai consigné les faits et gestes de {name} dans mes mémoires. Le chapitre est court, mais très annoté. »"],
      ["Chevalier aiguille Leda", "« {name} cherche Miquella avec nous. Enfin, {il} cherche surtout des fragments. Je ne juge pas. Si, un peu. »"],
      ["Freyja à crinière rouge", "« {name} se bat comme un général. Un général un peu en retard, mais un général. »"],
    ],
  },
  register: {
    motives: [
      "renouvellement de grâce", "réclamation au sujet d'une falaise", "recherche d'un Doigt compétent",
      "dépôt de runes (montant illisible)", "rendez-vous avec les Deux Doigts, reporté", "perte d'un sifflet spectral",
      "demande d'accès à Leyndell, refusée", "consultation au sujet d'une prophétie mal comprise",
      "réparation d'un bouclier en bois, sans espoir", "renseignements sur un certain « {caste} »",
    ],
    notes: [
      "semble connaître « {caste} » mieux qu'{il} ne l'admet.",
      "a demandé où se trouvaient les commodités ; la question reste ouverte.",
      "a laissé un message au sol dans le hall, très mal noté.",
      "est reparti{e} avec une épée qui n'était pas la sienne.",
      "a tenté de régler en larmes écarlates.",
      "a salué une statue en la prenant pour D.",
      "attend toujours que Hewg lève les yeux.",
      "a réclamé un reçu aux Deux Doigts, qui n'en délivrent pas.",
      "s'est assoupi{e} sur la table ronde, qui n'est d'ailleurs pas ronde.",
    ],
  },
  groundMessage: {
    places: [
      "l'entrée du château de Godrick", "un pont de Liurnia", "une falaise de Caelid", "la grande porte de Leyndell",
      "un coffre un peu trop accueillant", "la brume d'un boss", "l'ascenseur de Raya Lucaria", "un puits de Siofra",
      "l'autel de l'église d'Elleh", "un tunnel de Nécrolimbe",
    ],
    messages: [
      "Ici, peut-être un trésor. Ou peut-être un regret.", "Essayez la patience.", "Prudence : honnêteté devant.",
      "Fortement recommandé : ne pas.", "Voici une porte. Et pourtant, un mur.", "Si seulement j'avais une fiole…",
      "Visions de liberté, puis de falaise.", "Courage, presque fini. (Faux.)", "Attention : {caste} devant.",
      "Ce n'est pas un raccourci.", "Saut recommandé. Atterrissage non garanti.",
    ],
  },
  inventory: {
    items: [
      "une épée prêtée par Alexander", "deux fioles vides", "une carte de Caelid annotée « non »",
      "une rune qu'{il} jure dorée", "le sifflet de Torrent", "un pot de feu jamais lancé",
      "une clé de cachot sans cachot", "un message au sol plié en quatre", "une plume de corbeau de Liurnia",
      "une cendre d'esprit qui boude", "trois racines de mort pour Gurranq", "un bouclier en bois rongé",
      "la recette d'une graisse inutile", "un caillou d'albâtre sans usage connu", "un parchemin illisible de Rennala",
      "une lanterne achetée deux fois",
    ],
    comments: [
      "Rien à déclarer à la douane de la Table ronde.",
      "La liste a été certifiée conforme par un squelette.",
      "Tout le reste a été perdu au pied de « {caste} ».",
      "Le tout tient dans une poche, la physique étant ici conciliante.",
      "Les runes, elles, attendent sagement à l'endroit de la chute.",
    ],
  },
  letter: {
    recipients: ["Marika", "la Volonté supérieure", "Ranni", "Torrent", "son ancien maître d'armes", "l'Arbre-Monde", "Melina"],
    bodies: [
      "Je reviens bientôt. J'ai juste un boss à finir, puis un autre, puis je ne sais plus.",
      "J'ai bien reçu la grâce. Pourriez-vous préciser la date de retour prévue ?",
      "Je vous écris depuis le même site de grâce que la dernière fois. Rien n'a changé, sauf moi, un peu.",
      "Merci pour l'immortalité. Petite remarque constructive : elle fatigue.",
      "On m'appelle “{surnom}”. Je n'ai rien demandé, mais je m'y fais.",
      "J'ai croisé “{caste}”. Nous avons convenu de ne plus en parler.",
      "Je tiens bon. Les falaises, beaucoup moins.",
    ],
  },
};
