// Matière des titres, fiches et descriptions — uniquement des éléments du lore d'Elden Ring.
// Paires [masculin, féminin]. Dans les phrases : {name} prénom, {e} « e » au féminin,
// {il}/{Il} il/elle, {le} le/la (complément), {lui} lui/elle (après préposition),
// {caste} némésis tirée de la base, {title} titre complet, {surnom} partie du titre après le prénom,
// {aff} appartenance avec article, {deAff} « de » + appartenance, {classe}, {deClasse}, {level}, {n}.

window.ER_TITLES = {
  // Titres portés par des personnages du jeu (Chevalier limier Darriwil, Doigt sanglant Nerijus, Castellan Edgar…)
  honorifics: [
    ["Chevalier limier", "Chevalière limier"], ["Chevalier du Creuset", "Chevalière du Creuset"],
    ["Chevalier banni", "Chevalière bannie"], ["Chevalier royal", "Chevalière royale"], ["Chevalier carien", "Chevalière carienne"],
    ["Mage de guerre", "Mage de guerre"], ["Nécromancien", "Nécromancienne"], ["Parfumeur", "Parfumeuse"],
    ["Commandant", "Commandante"], ["Castellan", "Castellane"], ["Doigt sanglant", "Doigt sanglant"],
    ["Récusant", "Récusante"], ["Précepteur", "Préceptrice"], ["Sorcier", "Sorcière"], ["Gardien", "Gardienne"],
    ["Maître forgeron", "Maîtresse forgeronne"], ["Chasseur de sorcières", "Chasseuse de sorcières"],
  ],
  dlcHonorifics: [
    ["Chevalier aiguille", "Chevalière aiguille"], ["Chevalier noir", "Chevalière noire"],
    ["Lame de la Nuit", "Lame de la Nuit"], ["Chevalier de feu", "Chevalière de feu"],
  ],
  places: [
    "de Nécrolimbe", "de Liurnia", "de Caelid", "de Raya Lucaria", "de Leyndell", "de Farum Azula",
    "de Mohgwyn", "de Nokron", "de l'Arbre-Saint", "de Siofra", "de Sellia", "du mont Gelmir",
    "du plateau d'Altus", "du Manoir du Volcan", "de Caria", "d'Elphael", "de Morne",
  ],
  dlcPlaces: ["de l'Arbre-Ombre", "du Donjon de l'Ombre", "des terres de l'Ombre"],
};

window.ER_SHEET = {
  // [nom affiché, forme avec article]
  affiliations: [
    ["Famille royale carienne", "la Famille royale carienne"], ["Lignée dorée", "la Lignée dorée"],
    ["Réprouvés", "les Réprouvés"], ["Albinauréens", "les Albinauréens"],
    ["Hommes-bêtes de Farum Azula", "les Hommes-bêtes de Farum Azula"], ["Cristalliens", "les Cristalliens"],
    ["Semi-humains", "les Semi-humains"], ["Ordre d'or", "l'Ordre d'or"],
    ["Fidèles de la Flamme de la Frénésie", "les Fidèles de la Flamme de la Frénésie"],
    ["Doigts sanglants du Manoir du Volcan", "les Doigts sanglants du Manoir du Volcan"],
    ["Académie de Raya Lucaria", "l'Académie de Raya Lucaria"], ["Chevaliers du Creuset", "les Chevaliers du Creuset"],
    ["Assassins des Couteaux noirs", "les Assassins des Couteaux noirs"], ["Marchands nomades", "les Marchands nomades"],
    ["Dynastie de Mohgwyn", "la Dynastie de Mohgwyn"], ["Soldats de Godrick", "les Soldats de Godrick"],
    ["Chevaliers de Leyndell", "les Chevaliers de Leyndell"], ["Chevaliers de l'Arbre-Saint", "les Chevaliers de l'Arbre-Saint"],
    ["Fidèles ancestraux", "les Fidèles ancestraux"], ["Nox de la Cité éternelle", "les Nox de la Cité éternelle"],
    ["Géants de feu", "les Géants de feu"], ["Fidèles des Deux Doigts", "les Fidèles des Deux Doigts"],
    ["Sans-éclat", "les Sans-éclat"],
  ],
  dlcAffiliations: [
    ["Armée de Messmer", "l'Armée de Messmer"], ["Fidèles de Miquella", "les Fidèles de Miquella"],
    ["Chevaliers de feu de Messmer", "les Chevaliers de feu de Messmer"],
  ],
  // Classes de départ et leurs attributs de base : VIG ESP END FOR DEX INT FOI ÉSO
  classes: [
    ["Vagabond", [15, 10, 11, 14, 13, 9, 9, 7]], ["Guerrier", [11, 12, 11, 10, 16, 10, 8, 9]],
    ["Héros", [14, 9, 12, 16, 9, 7, 8, 11]], ["Bandit", [10, 11, 10, 9, 13, 9, 8, 14]],
    ["Astrologue", [9, 15, 9, 8, 12, 16, 7, 9]], ["Prophète", [10, 14, 8, 11, 10, 7, 16, 10]],
    ["Samouraï", [12, 11, 13, 12, 15, 9, 8, 8]], ["Prisonnier", [11, 12, 11, 11, 14, 14, 6, 9]],
    ["Confesseur", [10, 13, 10, 12, 12, 9, 14, 9]], ["Misérable", [10, 10, 10, 10, 10, 10, 10, 10]],
  ],
  attributes: ["Vigueur", "Esprit", "Endurance", "Force", "Dextérité", "Intelligence", "Foi", "Ésotérisme"],
  short: ["VIG", "ESP", "END", "FOR", "DEX", "INT", "FOI", "ÉSO"],
  weapons: [
    "Uchigatana", "Claymore", "Zweihänder", "Hallebarde", "Rapière", "Estoc", "Arc long", "Grande hache",
    "Fléau", "Griffes", "Fouet", "Bâton de pierre d'éclat", "Sceau sacré", "Lance", "Marteau de guerre", "Dague",
  ],
  spirits: [
    "Cendres de loups solitaires", "Cendres de la Larme mimétique", "Cendres de méduse", "Cendres de squelettes",
    "Cendres de Tiche des Couteaux noirs", "Cendres de Latenna l'Albinauréenne",
  ],
  runes: [
    "Grande Rune de Godrick", "Grande Rune de Rennala", "Grande Rune de Radahn", "Grande Rune de Rykard",
    "Grande Rune de Morgott", "Grande Rune de Mohg", "Grande Rune de Malenia",
  ],
  weaknesses: ["Putréfaction écarlate", "Saignement", "Gel", "Sommeil", "Folie", "Poison", "Feu", "Foudre", "Sacré", "Magie"],
  regions: ["Nécrolimbe", "Liurnia des Lacs", "Caelid", "le plateau d'Altus", "le mont Gelmir", "Leyndell", "les Montagnes des Géants", "Siofra", "Nokron"],
};

window.ER_LORE = {
  openings: [
    "Quand le Cercle d'Elden vola en éclats, {name} était ailleurs, ce qu'{il} considère encore comme une circonstance atténuante.",
    "Rappelé{e} par la grâce après une mort longue et reposante, {name} a repris la route de l'Arbre-Monde sans conviction excessive.",
    "{name} a franchi la brume de Margit au onzième essai, ce qu'{il} présente désormais comme une stratégie.",
    "À la Table ronde, Hewg forge pour {name} sans lever les yeux, ce qui reste la plus haute marque d'estime du bâtiment.",
    "{name} a aidé Alexander, le guerrier-jarre, à sortir du trou où il méditait. Depuis, la jarre lui écrit.",
    "Rennala berce toujours son œuf d'ambre au fond de Raya Lucaria ; {name} reste la seule personne à avoir frappé avant d'entrer.",
    "{name} a vu Radahn retenir les étoiles, et en a surtout retenu le cheval, qui mérite selon {lui} une médaille.",
    "Kalé, à l'église d'Elleh, a vendu à {name} une lanterne, deux cartes et le sentiment d'avoir été compris{e}.",
    "Melina a proposé à {name} de convertir ses runes en force ; {il} a demandé s'il existait une formule sans engagement.",
    "Patches a surgi d'un coffre en hurlant, puis s'est rendu avec une telle sincérité que {name} lui a laissé un pourboire.",
    "Gurranq a confié à {name} une liste de racines de mort à rapporter, griffonnée au dos d'un très vieux parchemin.",
    "{name} a porté la poupée de Ranni pendant des semaines, en lui parlant de la météo pour meubler.",
    "Fia a proposé à {name} une étreinte au chevet des morts ; {il} a sollicité un délai de réflexion de quarante jours.",
    "Boc le couturier a retouché l'armure de {name} en signalant, avec tact, que ce n'était pas la taille du dessus.",
    "Morgott a fait savoir à {name} que les Sans-éclat ne sont pas les bienvenus à Leyndell ; {il} l'a noté dans le livre d'or.",
    "Au Manoir du Volcan, Tanith a confié un contrat à {name}, rédigé si petit qu'{il} l'a signé par lassitude.",
    "Roderika accorde désormais les esprits de {name} ; ils chantent juste mais arrivent toujours en retard.",
    "{name} a suivi les messages au sol jusqu'au bord d'une falaise, puis un peu au-delà, par politesse.",
    "Le jour où {name} a compris que Marika et Radagon ne faisaient qu'un, {il} a relu tout son carnet avec un autre œil.",
    "{name} a gravi les Montagnes des Géants en manteau de mi-saison, par principe plus que par confort.",
    "Dans les égouts de Leyndell, {name} a croisé des Réprouvés fort aimables, à condition de ne pas les regarder.",
    "Godrick a proposé à {name} de rejoindre sa collection de bras ; {il} a décliné poliment, en gardant les deux.",
    "{name} a traversé Caelid sans s'arrêter, ce qui reste la seule façon raisonnable de traverser Caelid.",
    "Ranni a confié à {name} une mission sous les étoiles, en omettant de préciser lesquelles.",
  ],
  dlcOpenings: [
    "{name} a posé la main sur le bras desséché de Mohg et s'est réveillé{e} dans les terres de l'Ombre, sans bagages ni explication.",
    "Dans les terres de l'Ombre, {name} ramasse des fragments de l'Arbre-Ombre avec la ferveur d'un philatéliste.",
    "{name} a croisé Messmer l'Empaleur et garde de la rencontre une odeur de brûlé qui ne part pas au lavage.",
    "Leda a recruté {name} pour retrouver Miquella, puis a semblé vexée d'apprendre qu'{il} lisait les petites lignes.",
    "{name} a écouté Ansbach raconter Mohg pendant une soirée entière ; c'était très documenté et légèrement inquiétant.",
    "Igon a enseigné à {name} la haine des dragons avec la patience d'un moniteur d'auto-école.",
  ],
  middles: [
    "Issu{e} {deAff}, {il} entretient avec sa némésis, {caste}, une rivalité que les érudits jugent disproportionnée.",
    "Comme tout membre {deAff}, {il} considère sa némésis, {caste}, comme un problème de voisinage plutôt que comme un ennemi.",
    "Au sein {deAff}, on {le} compte parmi les membres, avec une réticence consignée en bas de page.",
    "Sa némésis, {caste}, l'a vaincu{e} quarante-trois fois ; {il} parle pudiquement d'un match nul prolongé.",
    "On l'a vu{e} attendre sa némésis, {caste}, devant une brume pendant trois jours, par pure politesse.",
    "Les archives {deAff} mentionnent un différend avec sa némésis, {caste}, au sujet d'une rune jamais rendue.",
    "{Il} a choisi la voie {deClasse} par vocation, et {aff} par erreur d'aiguillage.",
    "Formé{e} comme {classe}, {il} a rejoint {aff} pour la retraite, qui n'existe pas dans l'Entre-terre.",
    "Au niveau {level}, {il} affirme être à son meilleur, ce que sa némésis, {caste}, ne semble pas savoir.",
    "La surveillance de sa némésis, {caste}, lui a été confiée par {aff}, mission qu'{il} accomplit surtout de loin.",
  ],
  closings: [
    "Ses runes dorment sur un compte qui rapporte moins que ce que lui coûtent ses morts.",
    "{Il} tient un tableau de ses défaites, avec mise en forme conditionnelle.",
    "Le jour, {il} défie des demi-dieux ; le soir, {il} cherche en vain une vis manquante dans un meuble en kit.",
    "{Il} affirme avoir lu les conditions générales de la Volonté supérieure, ce que personne ne croit.",
    "Ses voisins ignorent tout de ses exploits, mais déplorent les coups de cloche d'invocation à trois heures du matin.",
    "{Il} garde ses fioles comme d'autres gardent leurs tickets de caisse : par principe, et sans jamais s'en servir.",
    "À chaque résurrection, {il} vérifie d'abord que ses clés sont bien dans sa poche.",
    "Son médecin traitant a cessé de poser des questions après le troisième certificat de décès.",
    "{Il} a demandé un devis pour réparer l'Arbre-Monde ; le délai était raisonnable, le prix beaucoup moins.",
    "{Il} salue les ennemis qui réapparaissent, comme on salue un collègue croisé deux fois dans le même couloir.",
    "Au guichet des âmes, {il} a pris un ticket ; son numéro n'est toujours pas passé.",
    "{Il} possède trois armes légendaires et une seule paire de chaussettes intacte.",
    "{Il} range sa Grande Rune dans le tiroir à piles, faute de mieux.",
    "{Il} règle sa grâce dorée en douze mensualités, sans frais.",
    "Sa carte de fidélité chez Kalé est pleine depuis longtemps ; la récompense n'a jamais été précisée.",
    "{Il} a fait relier ses messages au sol en un volume que personne n'a jamais emprunté.",
    "Ses attributs ont été vérifiés par un comptable de Leyndell, qui a démissionné juste après.",
    "{Il} n'a jamais compris pourquoi les coffres de l'Entre-terre sont si souvent habités.",
    "{Il} soigne son ego à la fiole écarlate et son orgueil à la fiole bleue, sans résultat notable.",
    "Sa monture spectrale a demandé un congé sabbatique, accordé à l'unanimité.",
  ],
  register: {
    motives: [
      "renouvellement de grâce", "réclamation au sujet d'une falaise", "recherche d'un Doigt compétent",
      "dépôt de runes, montant illisible", "rendez-vous avec les Deux Doigts, reporté", "perte d'un sifflet spectral",
      "demande d'accès à Leyndell, refusée", "consultation sur une prophétie mal comprise",
      "réparation d'un bouclier en bois, sans espoir", "renseignements sur sa némésis, {caste}",
    ],
    notes: [
      "semble connaître sa némésis, {caste}, mieux qu'{il} ne l'admet.",
      "a demandé où se trouvaient les commodités ; la question reste ouverte.",
      "a laissé un message au sol dans le hall, très mal noté.",
      "est reparti{e} avec une épée qui n'était pas la sienne.",
      "a tenté de régler en larmes écarlates.",
      "a salué une statue en la prenant pour D.",
      "attend toujours que Hewg lève les yeux.",
      "a réclamé un reçu aux Deux Doigts, qui n'en délivrent pas.",
      "s'est assoupi{e} sur la table ronde, qui n'est d'ailleurs pas ronde.",
    ],
  },
  inventory: {
    items: [
      "une épée prêtée par Alexander", "deux fioles vides", "une carte de Caelid annotée non merci",
      "une rune qu'{il} jure dorée", "le sifflet de Torrent", "un pot de feu jamais lancé",
      "une clé de cachot sans cachot", "un message au sol plié en quatre", "une plume de corbeau de Liurnia",
      "une cendre d'esprit qui boude", "trois racines de mort pour Gurranq", "un bouclier en bois rongé",
      "la recette d'une graisse inutile", "un caillou d'albâtre sans usage connu", "un parchemin illisible de Rennala",
      "une lanterne achetée deux fois",
    ],
    comments: [
      "Rien à déclarer à la douane de la Table ronde.",
      "La liste a été certifiée conforme par un squelette.",
      "Tout le reste a été perdu face à sa némésis, {caste}.",
      "Le tout tient dans une poche, la physique étant ici conciliante.",
      "Les runes, elles, attendent sagement à l'endroit de la chute.",
    ],
  },
  invasion: {
    results: [
      "match nul, les deux parties étant tombées du même pont",
      "victoire par abandon de la cible, partie se reposer à un site de grâce",
      "défaite, suivie d'une révérence courtoise",
      "indécis, la brume s'étant dissipée au mauvais moment",
      "victoire, contestée par un Doigt sanglant de passage",
      "annulée, la cible ayant invoqué trois amis et une méduse",
    ],
  },
};
